import "server-only";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import { getValidAccessToken } from "@/server/drive/tokens";
import {
  ensureFolderTree,
  downloadFile,
  uploadTextFile,
} from "@/server/drive/client";
import { transcribeAudio } from "@/server/ai/transcribe";
import { analyzeLecture, type LectureAnalysis } from "@/server/ai/tasks";
import { indexLectureChunks } from "@/server/search/index-lecture";
import type { Database, Json } from "@/lib/supabase/types";

interface SubjectInfo {
  id: string;
  name: string;
  year: number | null;
  semester: string | null;
}

function coerceSubject(value: unknown): SubjectInfo | null {
  const v = Array.isArray(value) ? value[0] : value;
  if (v && typeof v === "object" && "id" in v) return v as SubjectInfo;
  return null;
}

function renderSummaryMarkdown(title: string, a: LectureAnalysis): string {
  const list = (items: string[]) =>
    items.length ? items.map((i) => `- ${i}`).join("\n") : "_None_";
  const cards = a.revision.flashcards.length
    ? a.revision.flashcards.map((c) => `- **Q:** ${c.q}\n  **A:** ${c.a}`).join("\n")
    : "_None_";
  return [
    `# ${title}`,
    ``,
    `## Summary`,
    a.summary || "_None_",
    ``,
    `## Key concepts`,
    list(a.keyConcepts),
    ``,
    `## Important points`,
    list(a.importantPoints),
    ``,
    `## Topics`,
    list(a.topics),
    ``,
    `## Revision — likely exam questions`,
    list(a.revision.examQuestions),
    ``,
    `## Flashcards`,
    cards,
    ``,
    `## Quick review`,
    list(a.revision.quickReview),
    ``,
    `_Generated by ${a.provider} (${a.model})._`,
  ].join("\n");
}

/**
 * Full post-recording pipeline: download audio → transcribe → analyze →
 * persist transcript + summary → upload text files to Drive → index for RAG.
 * The audio is already safely stored, so a failure here leaves the lecture
 * "completed" (recording saved) with an error note rather than pretending it
 * failed outright.
 */
export async function processLecture(
  userId: string,
  lectureId: string,
): Promise<{ ok: boolean; error?: string }> {
  const db = getSupabaseAdmin();

  const { data: lecture } = await db
    .from("lectures")
    .select("id, title, drive_recording_file_id, subject:subjects(id, name, year, semester)")
    .eq("user_id", userId)
    .eq("id", lectureId)
    .maybeSingle();

  if (!lecture) return { ok: false, error: "not_found" };
  if (!lecture.drive_recording_file_id) return { ok: false, error: "no_audio" };
  const subject = coerceSubject(lecture.subject);
  const title = lecture.title ?? "Lecture";

  try {
    const token = await getValidAccessToken(userId);

    await db.from("lectures").update({ status: "transcribing" }).eq("id", lectureId);
    const audio = await downloadFile(token, lecture.drive_recording_file_id);
    const { text: transcript } = await transcribeAudio(audio, "audio/webm");
    await db
      .from("transcripts")
      .upsert(
        { lecture_id: lectureId, user_id: userId, content: transcript },
        { onConflict: "lecture_id" },
      );

    await db.from("lectures").update({ status: "summarizing" }).eq("id", lectureId);
    const analysis = await analyzeLecture(transcript, subject?.name ?? "Lecture");
    await db.from("summaries").upsert(
      {
        lecture_id: lectureId,
        user_id: userId,
        summary: analysis.summary,
        key_concepts: analysis.keyConcepts,
        important_points: analysis.importantPoints,
        topics: analysis.topics,
        revision: analysis.revision as unknown as Json,
        model: analysis.model,
      },
      { onConflict: "lecture_id" },
    );

    const finalTitle = analysis.title || title;
    const patch: Database["public"]["Tables"]["lectures"]["Update"] = {
      status: "completed",
      title: finalTitle,
      error: null,
    };

    if (subject) {
      const tree = await ensureFolderTree(userId, token, {
        year: subject.year,
        semester: subject.semester,
        subject: subject.name,
      });
      patch.drive_transcript_file_id = await uploadTextFile(
        token,
        tree.leaves.Transcripts,
        `${finalTitle}.txt`,
        transcript,
      );
      patch.drive_summary_file_id = await uploadTextFile(
        token,
        tree.leaves.Summaries,
        `${finalTitle}.md`,
        renderSummaryMarkdown(finalTitle, analysis),
        "text/markdown",
      );
    }

    await db.from("lectures").update(patch).eq("id", lectureId);
    await indexLectureChunks({
      userId,
      lectureId,
      subjectId: subject?.id ?? null,
      transcript,
      summary: analysis.summary,
    });

    return { ok: true };
  } catch (e) {
    await db
      .from("lectures")
      .update({
        status: "completed",
        error: e instanceof Error ? e.message : "processing_failed",
      })
      .eq("id", lectureId);
    return { ok: false, error: e instanceof Error ? e.message : "processing_failed" };
  }
}
